# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: James Woodfield
title: Postdoc Research Assistant Mathematics
email: james14641@gmail.com
website: https://james14641.github.io
"Google Scholar": https://scholar.google.com/citations?user=mAwYQ9AAAAAJ&hl=en

# Dark Mode (true/false/never)
darkmode: false
# Social links
#twitter_username: none
github_username:  james14641
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000
# Additional icon links
additional_links:
- title: Scholar
  icon: google_scholar_2.png #fas fa-globe
  url: https://scholar.google.com/citations?user=mAwYQ9AAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
   Hi, my name's Woody, I'm a postdoc researcher at Imperial College London.

    # My Research Interests:
    1. **Scientific Computing**
    2. **Numerical Methods**
    3. **Data Assimilation**
    4. **Fluid Mechanics**
    5. **Machine Learning**


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Point vortex solver 
        link: https://github.com/James14641/Point_vortex
        # link_text: Project Website
        additional_links:
          - title: Papers associated
            icon: fab fa-file-pdf
            url: https://arxiv.org/pdf/2405.00640       # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Inviscid vortex method, 
        description: | # this will include new lines to allow paragraphs
          This is a stochastic invisid vortex method describing two dimensional fluid flow. 
          In we use the CRPS as en enseble forecast inspired loss function,
          with respect to data to calibrate the basis of noise. 


      - layout: top-middle
        title: Data Assimilation
        link: https://github.com/James14641/Particle_filter
        # link_text: Project Website
        additional_links:
          - title:  Papers associated
            icon: fab fa-github
            link: To be appearing
        quote: >
          Collaborative project with A. Lobbe: 
        description: | # this will include new lines to allow paragraphs
          A sandbox for exploring (stochastic)Exponential Time Differencing (ETD) and Stochastic Integrating Factor (SIF) methods in the context of data assimilation using particle filters and Kalman filters

          This repository serves as a flexible platform for testing time-stepping schemes, stochastic integration strategies, and data assimilation algorithms



      - layout: top-middle
        title: Exponential time integration
        link: github.com/functioning_link
        # link_text: Project Website
        additional_links:
          - title:  Papers associated
            icon: fab fa-github
            url: github.com/link_to_functioning_website
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is going to be a link to a solver. 
        description: | # this will include new lines to allow paragraphs
          This is the solver associated with a ff exponential time integration.  


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Postdoc
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Postdoc Research Assistant Mathematics
        caption: 2022 - Present
        quote: >
          no quote
        description: | # this will include new lines to allow paragraphs
          Stuod research project
        url: https://www.imperial.ac.uk/ocean-dynamics-synergy/

#-Present & Postdoc Research Assistant Mathematics, Imperial College London, UK
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Reading University
        caption: 2019 - 2022
        sub_title: PhD Mathematics
        quote: >
            Time-stepping schemes allowing long timesteps
        description: | # this will include new lines to allow paragraphs
          In the context of the next generation of numerical weather prediction models,
          dynamical cores require time-stepping schemes that are: 
          Consistent, 
          Linear invariant,
          Conserve mass locally, 
          preserve nonlinearstability properties,
          and remain stable at large timesteps.

      - layout: left
        title: Imperial College London 
        caption: 2018 - 2019
        sub_title: Mres Mathematics
        quote: >
            no quote yet
        description: | # this will include new lines to allow paragraphs
          Multisymplectic methods in the context of 
      - layout: left
        title: University of Oxford
        caption: 2014 - 2018
        sub_title: MMath Mathematics
        quote: >
            no quote yet
        description: | # this will include new lines to allow paragraphs
          Available debt-free online:
        url: https://courses.maths.ox.ac.uk/course/index.php?categoryid=9
        
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      List of interests:
      - Outdoors
      - Racket sports

      This is how to add image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag